# frozen_string_literal: true

module CopyBashScripts
  BIN_DIR = "#{RbConfig::TOPDIR}/bin"

  SRC_DIR = "#{Dir.pwd}/src/bin"

  class << self

    def run
      # clean empty gem folders, needed as of 2019-10-20
      ary = Dir["#{Gem.dir}/gems/*"]
      ary.each { |d| Dir.rmdir(d) if Dir.empty?(d) }

      bins = Dir["#{SRC_DIR}/*"]

      bins.each do |fn|
        str = File.read(fn, mode: 'rb:UTF-8').sub(/^#![^\n]+ruby/, '#!/usr/bin/env ruby')
        base = File.basename fn
        File.write "#{BIN_DIR}/#{base}", str, mode: 'wb:UTF-8'
      end

      # rake bash bin file
      fn = "#{BIN_DIR}/rake"
      str = File.read(fn, mode: 'rb:UTF-8').sub(/\A.+?ruby$/m, '#!/usr/bin/env ruby')
      File.write fn, str, mode: 'wb:UTF-8'

      # below replaces code in cmd files with hard coded paths
      new_cmd = <<NEW_CMD.rstrip
:""||{ ""=> %q<-*- ruby -*-
@"%~dp0ruby" -x "%~f0" %*
@exit /b %ERRORLEVEL%
};{#
bindir="${0%/*}" #
exec "$bindir/ruby" "-x" "$0" "$@" #
>,
}
#!/usr/bin/env ruby
#
# This file was generated by RubyGems.
#
# The application 'rake' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'
NEW_CMD

      bins = Dir["#{BIN_DIR}/*.cmd"]
      bins.each do |fn|
        str = File.read(fn, mode: 'rb:UTF-8').sub(/.+?require 'rubygems'$/m, new_cmd)
        base = File.basename fn
        File.write "#{BIN_DIR}/#{base}", str, mode: 'wb:UTF-8'
      end
    end
  end
end
CopyBashScripts.run
